version: "3.9"

services:
  api:
    container_name: meerve-api
    image: meerve-api
    restart: always
    build: ./backend
    ports:
      - 3001:3001
    links:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    networks:
      - meerve-net
  web:
    container_name: meerve-web
    image: meerve-web
    restart: always
    ports:
      - 3000:3000
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    links:
      - api
    depends_on:
      - api
    networks:
      - meerve-net
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    networks:
      - meerve-net
  nginx:
    container_name: meerve-nginx
    image: meerve-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - meerve-net

networks:
  meerve-net:
    driver: bridge

volumes:
  data-volume:
